services:
  db:
    image: postgres:16
    container_name: mohanet_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mohanet_adatbazis
      # env DATABASE_URL=postgres://user:password@localhost:5432/POSTGRES_DB
      #DB_HOST=localhost
      #DB_PORT=5432
      #DB_USER=postgres
      #DB_PASSWORD=postgres
      #DB_NAME=mohanet
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
volumes:
  dbdata: