services:
  db:
    image: postgres:16
    container_name: mohanet_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mohanet_adatbazis # evn DATABASE_URL=postgres://user:password@localhost:5432/POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
volumes:
  dbdata: